// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZHyiU3liaM2pRC4Pah-QpAj66S_PPbCo',
    appId: '1:419979291766:web:202121ca366df481a4c357',
    messagingSenderId: '419979291766',
    projectId: 'recipe-58d0f',
    authDomain: 'recipe-58d0f.firebaseapp.com',
    storageBucket: 'recipe-58d0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz6HZVfEEhZD2Od8CrU1aScjT0L4c60js',
    appId: '1:419979291766:android:5cadc14e8bef717ea4c357',
    messagingSenderId: '419979291766',
    projectId: 'recipe-58d0f',
    storageBucket: 'recipe-58d0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1Q1351iNUn4r_E_1MlI2ww0lhpwsu1k',
    appId: '1:419979291766:ios:33135d9a00630855a4c357',
    messagingSenderId: '419979291766',
    projectId: 'recipe-58d0f',
    storageBucket: 'recipe-58d0f.firebasestorage.app',
    iosBundleId: 'com.example.reciepes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1Q1351iNUn4r_E_1MlI2ww0lhpwsu1k',
    appId: '1:419979291766:ios:33135d9a00630855a4c357',
    messagingSenderId: '419979291766',
    projectId: 'recipe-58d0f',
    storageBucket: 'recipe-58d0f.firebasestorage.app',
    iosBundleId: 'com.example.reciepes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZHyiU3liaM2pRC4Pah-QpAj66S_PPbCo',
    appId: '1:419979291766:web:1b7d5b8ea3d312b8a4c357',
    messagingSenderId: '419979291766',
    projectId: 'recipe-58d0f',
    authDomain: 'recipe-58d0f.firebaseapp.com',
    storageBucket: 'recipe-58d0f.firebasestorage.app',
  );
}
